
create table if not exists employee 
(
  	id bigint generated by default as identity (start with 1, increment by 1) not null,
   	emp_name varchar(50) NOT NULL,
	emp_designation varchar(50)  NOT NULL,
  	emp_salary double NOT NULL,
   	primary key (id)
);
